<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Laminas MVC')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?= $this->headLink([
            'rel' => 'shortcut icon', 
            'type' => 'image/vnd.microsoft.icon', 
            'href' => $this->basePath('/library/basic/img/favicon.ico')
            ])
            ->prependStylesheet($this->basePath('library/basic/css/css.css'))
            ->prependStylesheet($this->basePath('library/bootstrap-5.1.0/css/bootstrap.min.css'))
        ?>

        <?= $this->headScript() ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button
                        class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                    >
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('library/basic/img/laminas-logo.svg') ?>" alt="Laminas">MVC Skeleton
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('home') ?>">Home</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('system-config') ?>">Thiết lập chung</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('system-user') ?>">Tài khoản</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('category-partner') ?>">Đối tác</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('category-goods') ?>">Hàng hóa</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('content-menu') ?>">Hệ thống menu</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('content-content') ?>">Danh mục nội dung</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('content-block') ?>">Khối nội dung</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('front-vote') ?>">Bình chọn</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('front-contact') ?>">Liên hệ</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>
                    &copy; <?= date('Y') ?>
                    <a href="https://getlaminas.org/">Laminas Project</a> a Series of LF Projects, LLC.
                </p>
            </footer>
        </div>

        
        <?= $this->inlineScript()
            ->prependFile($this->basePath('library/bootstrap-5.1.0/js/bootstrap.min.js'))
            ->prependFile($this->basePath('library/basic/js/jquery-3.6.0.min.js')) 
        ?>
    </body>
</html>
